In [1]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()#鸢(yuan)尾花数据集
x=iris.data
y=iris.target
print(x[:10])#4个特征
print(y)#3类

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)#分割训练和测试数据集

In [3]:
#使用sklearn导入高斯朴素贝叶斯，多项式朴素贝叶斯，伯努力朴素贝叶斯并训练
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
clf1 = GaussianNB()
clf1.fit(x_train,y_train)

clf2 = MultinomialNB()
clf2.fit(x_train,y_train)

clf3 = BernoulliNB()
clf3.fit(x_train,y_train)

BernoulliNB()

In [4]:
#在测试集预测结果
def print_predict(clf):
    y_predict=clf.predict(x_test)
    y_proba=clf.predict_proba(x_test)
    print(y_predict[:3])
    print(y_proba[:3])

print('Gauss:')
print_predict(clf1)
print('\nMulti:')
print_predict(clf2)
print('\nBernou:')
print_predict(clf3)

Gauss:
[0 1 1]
[[1.00000000e+000 4.63122558e-018 1.75152668e-028]
 [3.98750134e-075 9.99993195e-001 6.80464396e-006]
 [5.59763708e-126 9.38447095e-001 6.15529050e-002]]

Multi:
[0 1 1]
[[0.76836453 0.15776562 0.07386985]
 [0.07340508 0.52088732 0.4057076 ]
 [0.04368014 0.53341703 0.42290283]]

Bernou:
[0 0 0]
[[0.34968097 0.34968097 0.30063805]
 [0.34968097 0.34968097 0.30063805]
 [0.34968097 0.34968097 0.30063805]]


In [5]:
#输出指标
from sklearn.metrics import accuracy_score,precision_score,recall_score
def print_clf_metrics(y_true, y_pred):
    acc=accuracy_score(y_true,y_pred)
    pre=precision_score(y_true,y_pred,average=None)
    recall=recall_score(y_true,y_pred,average=None)
    print('accuracy:{:.2f}%'.format(100*acc))
    print('precision:{}%'.format(np.round(100*pre,2)))
    print('recall:{}%'.format(np.round(100*recall,2)))
    
print('Gauss:')
print_clf_metrics(y_test,clf1.predict(x_test))
print('\nMulti:')
print_clf_metrics(y_test,clf2.predict(x_test))
print('\nBernou:')
print_clf_metrics(y_test,clf3.predict(x_test))

Gauss:
accuracy:92.11%
precision:[100.    83.33  93.33]%
recall:[100.    90.91  87.5 ]%

Multi:
accuracy:71.05%
precision:[100.  50. 100.]%
recall:[100.   100.    31.25]%

Bernou:
accuracy:28.95%
precision:[28.95  0.    0.  ]%
recall:[100.   0.   0.]%


/home/zdk/software/anaconda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


总结：
1. 一般来说，如果样本特征的分布大部分是连续值，使用GaussianNB会比较好。
2. 如果如果样本特征的分布大部分是多元离散值，使用MultinomialNB比较合适。
3. 而如果样本特征是二元离散值或者很稀疏的多元离散值，应该使用BernoulliNB